apiVersion: __KubernetesApi__
kind: CronJob
metadata:
  name: auto-upgrade-cronjob
  labels:
    app: agent
    openhorizon.org/component: agent
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: agent
            openhorizon.org/component: agent
        spec:
          volumes:
          - name: agent-pvc-storage
            persistentVolumeClaim:
              claimName: openhorizon-agent-pvc
          # START_REMOTE_ICR
          imagePullSecrets:
          - name: registry-creds
          # END_REMOTE_ICR
          containers:
          - name: agent-auto-upgrade
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: ["ALL"]
            image: '__ImagePath__'
            command:
              - /bin/sh
              - '-c'
              - >-
                /usr/local/bin/auto-upgrade-cronjob.sh
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /var/horizon
              name: agent-pvc-storage
              subPath: horizon
            env:
            - name: CRONJOB_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_NAMESPACE
              value:  __AgentNameSpace__
          restartPolicy: Never
          serviceAccountName: __ServiceAccount__
          serviceAccount: __ServiceAccount__